# coding: utf-8

from __future__ import absolute_import
#from django.db.models import Model
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Size(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, h: int=None, resize: str=None, w: int=None):
        """
        Size - a model defined in Swagger

        :param h: The h of this Size.
        :type h: int
        :param resize: The resize of this Size.
        :type resize: str
        :param w: The w of this Size.
        :type w: int
        """
        self.swagger_types = {
            'h': int,
            'resize': str,
            'w': int
        }

        self.attribute_map = {
            'h': 'h',
            'resize': 'resize',
            'w': 'w'
        }

        self._h = h
        self._resize = resize
        self._w = w

    @classmethod
    def from_dict(cls, dikt) -> 'Size':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Size of this Size.
        :rtype: Size
        """
        return deserialize_model(dikt, cls)

    @property
    def h(self) -> int:
        """
        Gets the h of this Size.

        :return: The h of this Size.
        :rtype: int
        """
        return self._h

    @h.setter
    def h(self, h: int):
        """
        Sets the h of this Size.

        :param h: The h of this Size.
        :type h: int
        """

        self._h = h

    @property
    def resize(self) -> str:
        """
        Gets the resize of this Size.

        :return: The resize of this Size.
        :rtype: str
        """
        return self._resize

    @resize.setter
    def resize(self, resize: str):
        """
        Sets the resize of this Size.

        :param resize: The resize of this Size.
        :type resize: str
        """

        self._resize = resize

    @property
    def w(self) -> int:
        """
        Gets the w of this Size.

        :return: The w of this Size.
        :rtype: int
        """
        return self._w

    @w.setter
    def w(self, w: int):
        """
        Sets the w of this Size.

        :param w: The w of this Size.
        :type w: int
        """

        self._w = w

